### ISSUE TITLE
Proposal: Show appropriate error when app with native extensions are built with unsupported builder

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/npm-install#133]
**Problem**:  For most apps, npm-install runs fine on the base builder. But when the app requires compilation of native extensions using `node-gyp`, the buildpack requires the full builder because node-gyp requires python and the module may require other shared objects.

### Reproducing the issue

1. Remove the `builder` line in [integration.json](https://github.com/paketo-buildpacks/npm-install/blob/v0.2.0/integration.json#L2)

2. Run [this test](https://github.com/paketo-buildpacks/npm-install/blob/v0.2.0/integration/vendored_test.go#L110)

3. You can see it fails the build step with:
```
[builder] Paketo NPM Install Buildpack 1.2.3
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       node_modules      -> "Found"
[builder]       npm-cache         -> "Not found"
[builder]       package-lock.json -> "Found"
[builder] 
[builder]     Selected NPM build process: 'npm rebuild'
[builder] 
[builder]   Executing build process
[builder]     Running 'npm run-script preinstall --if-present'
[builder]     Running 'npm rebuild --nodedir=/layers/paketo-buildpacks_node-engine/node'
[builder]     vendored@0.0.1 /workspace
[builder]     +-- chalk-cli@3.0.0
[builder] npm rebuild failed: exit status 1
[builder]     | +-- arr-exclude@1.0.0
[builder]     | +-- chalk@1.1.3
[builder]     | | +-- ansi-styles@2.2.1
[builder]     | | +-- escape-string-regexp@1.0.5
[builder]     | | +-- has-ansi@2.0.0
[builder]     | | | `-- ansi-regex@2.1.1
[builder]     | | +-- strip-ansi@3.0.1
[builder]     | | | `-- ansi-regex@2.1.1 deduped
[builder]     | | `-- supports-color@2.0.0
[builder]     | +-- dot-prop@3.0.0
[builder]     | | `-- is-obj@1.0.1
[builder]     | +-- get-stdin@5.0.1
[builder]     | `-- meow@3.7.0
[builder]     |   +-- camelcase-keys@2.1.0
[builder]     |   | +-- camelcase@2.1.1
[builder]     |   | `-- map-obj@1.0.1 deduped
[builder]     |   +-- decamelize@1.2.0
[builder]     |   +-- loud-rejection@1.6.0
[builder]     |   | +-- currently-unhandled@0.4.1
[builder]     |   | | `-- array-find-index@1.0.2
[builder]     |   | `-- signal-exit@3.0.2
[builder]     |   +-- map-obj@1.0.1
[builder]     |   +-- minimist@1.2.0
[builder]     |   +-- normalize-package-data@2.5.0
[builder]     |   | +-- hosted-git-info@2.8.5
[builder]     |   | +-- resolve@1.15.1
[builder]     |   | | `-- path-parse@1.0.6
[builder]     |   | +-- semver@5.7.1 deduped
[builder]     |   | `-- validate-npm-package-license@3.0.4
[builder]     |   |   +-- spdx-correct@3.1.0
[builder]     |   |   | +-- spdx-expression-parse@3.0.0 deduped
[builder]     |   |   | `-- spdx-license-ids@3.0.5
[builder]     |   |   `-- spdx-expression-parse@3.0.0
[builder]     |   |     +-- spdx-exceptions@2.2.0
[builder]     |   |     `-- spdx-license-ids@3.0.5 deduped
[builder]     |   +-- object-assign@4.1.1
[builder]     |   +-- read-pkg-up@1.0.1
[builder]     |   | +-- find-up@1.1.2
[builder]     |   | | +-- path-exists@2.1.0
[builder]     |   | | | `-- pinkie-promise@2.0.1 deduped
[builder]     |   | | `-- pinkie-promise@2.0.1
[builder]     |   | |   `-- pinkie@2.0.4
[builder]     |   | `-- read-pkg@1.1.0
[builder]     |   |   +-- load-json-file@1.1.0
[builder]     |   |   | +-- graceful-fs@4.2.3
[builder]     |   |   | +-- parse-json@2.2.0
[builder]     |   |   | | `-- error-ex@1.3.2
[builder]     |   |   | |   `-- is-arrayish@0.2.1
[builder]     |   |   | +-- pify@2.3.0
[builder]     |   |   | +-- pinkie-promise@2.0.1 deduped
[builder]     |   |   | `-- strip-bom@2.0.0
[builder]     |   |   |   `-- is-utf8@0.2.1
[builder]     |   |   +-- normalize-package-data@2.5.0 deduped
[builder]     |   |   `-- path-type@1.1.0
[builder]     |   |     +-- graceful-fs@4.2.3 deduped
[builder]     |   |     +-- pify@2.3.0 deduped
[builder]     |   |     `-- pinkie-promise@2.0.1 deduped
[builder]     |   +-- redent@1.0.0
[builder]     |   | +-- indent-string@2.1.0
[builder]     |   | | `-- repeating@2.0.1
[builder]     |   | |   `-- is-finite@1.1.0
[builder]     |   | `-- strip-indent@1.0.1
[builder]     |   |   `-- get-stdin@4.0.1
[builder]     |   `-- trim-newlines@1.0.0
[builder]     +-- node-pre-gyp@0.14.0
[builder]     | +-- detect-libc@1.0.3
[builder]     | +-- mkdirp@0.5.1
[builder]     | | `-- minimist@0.0.8
[builder]     | +-- needle@2.4.0
[builder]     | | +-- debug@3.2.6
[builder]     | | | `-- ms@2.1.2
[builder]     | | +-- iconv-lite@0.4.24
[builder]     | | | `-- safer-buffer@2.1.2
[builder]     | | `-- sax@1.2.4
[builder]     | +-- nopt@4.0.1
[builder]     | | +-- abbrev@1.1.1
[builder]     | | `-- osenv@0.1.5
[builder]     | |   +-- os-homedir@1.0.2
[builder]     | |   `-- os-tmpdir@1.0.2
[builder]     | +-- npm-packlist@1.4.7
[builder]     | | +-- ignore-walk@3.0.3
[builder]     | | | `-- minimatch@3.0.4
[builder]     | | |   `-- brace-expansion@1.1.11
[builder]     | | |     +-- balanced-match@1.0.0
[builder]     | | |     `-- concat-map@0.0.1
[builder]     | | `-- npm-bundled@1.1.1
[builder]     | |   `-- npm-normalize-package-bin@1.0.1
[builder]     | +-- npmlog@4.1.2
[builder]     | | +-- are-we-there-yet@1.1.5
[builder]     | | | +-- delegates@1.0.0
[builder]     | | | `-- readable-stream@2.3.7
[builder]     | | |   +-- core-util-is@1.0.2
[builder]     | | |   +-- inherits@2.0.4 deduped
[builder]     | | |   +-- isarray@1.0.0
[builder]     | | |   +-- process-nextick-args@2.0.1
[builder]     | | |   +-- safe-buffer@5.1.2 deduped
[builder]     | | |   +-- string_decoder@1.1.1
[builder]     | | |   | `-- safe-buffer@5.1.2 deduped
[builder]     | | |   `-- util-deprecate@1.0.2
[builder]     | | +-- console-control-strings@1.1.0
[builder]     | | +-- gauge@2.7.4
[builder]     | | | +-- aproba@1.2.0
[builder]     | | | +-- console-control-strings@1.1.0 deduped
[builder]     | | | +-- has-unicode@2.0.1
[builder]     | | | +-- object-assign@4.1.1 deduped
[builder]     | | | +-- signal-exit@3.0.2 deduped
[builder]     | | | +-- string-width@1.0.2
[builder]     | | | | +-- code-point-at@1.1.0
[builder]     | | | | +-- is-fullwidth-code-point@1.0.0
[builder]     | | | | | `-- number-is-nan@1.0.1
[builder]     | | | | `-- strip-ansi@3.0.1 deduped
[builder]     | | | +-- strip-ansi@3.0.1 deduped
[builder]     | | | `-- wide-align@1.1.3
[builder]     | | |   `-- string-width@1.0.2 deduped
[builder]     | | `-- set-blocking@2.0.0
[builder]     | +-- rc@1.2.8
[builder]     | | +-- deep-extend@0.6.0
[builder]     | | +-- ini@1.3.5
[builder]     | | +-- minimist@1.2.0
[builder]     | | `-- strip-json-comments@2.0.1
[builder]     | +-- rimraf@2.7.1
[builder]     | | `-- glob@7.1.6
[builder]     | |   +-- fs.realpath@1.0.0
[builder]     | |   +-- inflight@1.0.6
[builder]     | |   | +-- once@1.4.0 deduped
[builder]     | |   | `-- wrappy@1.0.2
[builder]     | |   +-- inherits@2.0.4
[builder]     | |   +-- minimatch@3.0.4 deduped
[builder]     | |   +-- once@1.4.0
[builder]     | |   | `-- wrappy@1.0.2 deduped
[builder]     | |   `-- path-is-absolute@1.0.1
[builder]     | +-- semver@5.7.1
[builder]     | `-- tar@4.4.13
[builder]     |   +-- chownr@1.1.3
[builder]     |   +-- fs-minipass@1.2.7
[builder]     |   | `-- minipass@2.9.0 deduped
[builder]     |   +-- minipass@2.9.0
[builder]     |   | +-- safe-buffer@5.1.2 deduped
[builder]     |   | `-- yallist@3.1.1 deduped
[builder]     |   +-- minizlib@1.3.3
[builder]     |   | `-- minipass@2.9.0 deduped
[builder]     |   +-- mkdirp@0.5.1 deduped
[builder]     |   +-- safe-buffer@5.1.2
[builder]     |   `-- yallist@3.1.1
[builder]     `-- sqlite3@4.1.1
[builder]       +-- nan@2.14.0
[builder]       +-- node-pre-gyp@0.11.0
[builder]       | +-- detect-libc@1.0.3 deduped
[builder]       | +-- mkdirp@0.5.1 deduped
[builder]       | +-- needle@2.4.0 deduped
[builder]       | +-- nopt@4.0.1 deduped
[builder]       | +-- npm-packlist@1.4.7 deduped
[builder]       | +-- npmlog@4.1.2 deduped
[builder]       | +-- rc@1.2.8 deduped
[builder]       | +-- rimraf@2.7.1 deduped
[builder]       | +-- semver@5.7.1 deduped
[builder]       | `-- tar@4.4.13 deduped
[builder]       `-- request@2.88.0
[builder]         +-- aws-sign2@0.7.0
[builder]         +-- aws4@1.9.0
[builder]         +-- caseless@0.12.0
[builder]         +-- combined-stream@1.0.8
[builder]         | `-- delayed-stream@1.0.0
[builder]         +-- extend@3.0.2
[builder]         +-- forever-agent@0.6.1
[builder]         +-- form-data@2.3.3
[builder]         | +-- asynckit@0.4.0
[builder]         | +-- combined-stream@1.0.8 deduped
[builder]         | `-- mime-types@2.1.26 deduped
[builder]         +-- har-validator@5.1.3
[builder]         | +-- ajv@6.10.2
[builder]         | | +-- fast-deep-equal@2.0.1
[builder]         | | +-- fast-json-stable-stringify@2.1.0
[builder]         | | +-- json-schema-traverse@0.4.1
[builder]         | | `-- uri-js@4.2.2
[builder]         | |   `-- punycode@2.1.1
[builder]         | `-- har-schema@2.0.0
[builder]         +-- http-signature@1.2.0
[builder]         | +-- assert-plus@1.0.0
[builder]         | +-- jsprim@1.4.1
[builder]         | | +-- assert-plus@1.0.0 deduped
[builder]         | | +-- extsprintf@1.3.0
[builder]         | | +-- json-schema@0.2.3
[builder]         | | `-- verror@1.10.0
[builder]         | |   +-- assert-plus@1.0.0 deduped
[builder]         | |   +-- core-util-is@1.0.2 deduped
[builder]         | |   `-- extsprintf@1.3.0 deduped
[builder]         | `-- sshpk@1.16.1
[builder]         |   +-- asn1@0.2.4
[builder]         |   | `-- safer-buffer@2.1.2 deduped
[builder]         |   +-- assert-plus@1.0.0 deduped
[builder]         |   +-- bcrypt-pbkdf@1.0.2
[builder]         |   | `-- tweetnacl@0.14.5 deduped
[builder]         |   +-- dashdash@1.14.1
[builder]         |   | `-- assert-plus@1.0.0 deduped
[builder]         |   +-- ecc-jsbn@0.1.2
[builder]         |   | +-- jsbn@0.1.1 deduped
[builder]         |   | `-- safer-buffer@2.1.2 deduped
[builder]         |   +-- getpass@0.1.7
[builder]         |   | `-- assert-plus@1.0.0 deduped
[builder]         |   +-- jsbn@0.1.1
[builder]         |   +-- safer-buffer@2.1.2 deduped
[builder]         |   `-- tweetnacl@0.14.5
[builder]         +-- is-typedarray@1.0.0
[builder]         +-- isstream@0.1.2
[builder]         +-- json-stringify-safe@5.0.1
[builder]         +-- mime-types@2.1.26
[builder]         | `-- mime-db@1.43.0
[builder]         +-- oauth-sign@0.9.0
[builder]         +-- performance-now@2.1.0
[builder]         +-- qs@6.5.2
[builder]         +-- safe-buffer@5.1.2 deduped
[builder]         +-- tough-cookie@2.4.3
[builder]         | +-- psl@1.7.0
[builder]         | `-- punycode@1.4.1
[builder]         +-- tunnel-agent@0.6.0
[builder]         | `-- safe-buffer@5.1.2 deduped
[builder]         `-- uuid@3.3.3
[builder]     
[builder]     
[builder]     > sqlite3@4.1.1 install /workspace/node_modules/sqlite3
[builder]     > node-pre-gyp install --fallback-to-build
[builder]     
[builder]     gyp ERR! find Python 
[builder]     gyp ERR! find Python Python is not set from command line or npm configuration
[builder]     gyp ERR! find Python Python is not set from environment variable PYTHON
[builder]     gyp ERR! find Python checking if "python" can be used
[builder]     gyp ERR! find Python - "python" is not in PATH or produced an error
[builder]     gyp ERR! find Python checking if "python2" can be used
[builder]     gyp ERR! find Python - "python2" is not in PATH or produced an error
[builder]     gyp ERR! find Python checking if "python3" can be used
[builder]     gyp ERR! find Python - "python3" is not in PATH or produced an error
[builder]     gyp ERR! find Python 
[builder]     gyp ERR! find Python **********************************************************
[builder]     gyp ERR! find Python You need to install the latest version of Python.
[builder]     gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[builder]     gyp ERR! find Python you can try one of the following options:
[builder]     gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
[builder]     gyp ERR! find Python   (accepted by both node-gyp and npm)
[builder]     gyp ERR! find Python - Set the environment variable PYTHON
[builder]     gyp ERR! find Python - Set the npm configuration variable python:
[builder]     gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
[builder]     gyp ERR! find Python For more information consult the documentation at:
[builder]     gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[builder]     gyp ERR! find Python **********************************************************
[builder]     gyp ERR! find Python 
[builder]     gyp ERR! configure error 
[builder]     gyp ERR! stack Error: Could not find any Python installation to use
[builder]     gyp ERR! stack     at PythonFinder.fail (/layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
[builder]     gyp ERR! stack     at PythonFinder.runChecks (/layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
[builder]     gyp ERR! stack     at PythonFinder.<anonymous> (/layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
[builder]     gyp ERR! stack     at PythonFinder.execFileCallback (/layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
[builder]     gyp ERR! stack     at exithandler (child_process.js:301:5)
[builder]     gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
[builder]     gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
[builder]     gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
[builder]     gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
[builder]     gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
[builder]     gyp ERR! System Linux 4.19.76-linuxkit
[builder]     gyp ERR! command "/layers/paketo-buildpacks_node-engine/node/bin/node" "/layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64" "--nodedir=/layers/paketo-buildpacks_node-engine/node"
[builder]     gyp ERR! cwd /layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3
[builder]     gyp ERR! node -v v10.22.0
[builder]     gyp ERR! node-gyp -v v5.1.0
[builder]     gyp ERR! not ok 
[builder]     node-pre-gyp ERR! build error 
[builder]     node-pre-gyp ERR! stack Error: Failed to execute '/layers/paketo-buildpacks_node-engine/node/bin/node /layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64 --nodedir=/layers/paketo-buildpacks_node-engine/node' (1)
[builder]     node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[builder]     node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
[builder]     node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
[builder]     node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[builder]     node-pre-gyp ERR! System Linux 4.19.76-linuxkit
[builder]     node-pre-gyp ERR! command "/layers/paketo-buildpacks_node-engine/node/bin/node" "/workspace/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[builder]     node-pre-gyp ERR! cwd /layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3
[builder]     node-pre-gyp ERR! node -v v10.22.0
[builder]     node-pre-gyp ERR! node-pre-gyp -v v0.11.0
[builder]     node-pre-gyp ERR! not ok 
[builder]     Failed to execute '/layers/paketo-buildpacks_node-engine/node/bin/node /layers/paketo-buildpacks_node-engine/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/layers/paketo-buildpacks_npm-install/modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64 --nodedir=/layers/paketo-buildpacks_node-engine/node' (1)
[builder]     npm ERR! code ELIFECYCLE
[builder]     npm ERR! errno 1
[builder]     npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
[builder]     npm ERR! Exit status 1
[builder]     npm ERR! 
[builder]     npm ERR! Failed at the sqlite3@4.1.1 install script.
[builder]     npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[builder]     
[builder]     npm ERR! A complete log of this run can be found in:
[builder]     npm ERR!     /home/cnb/.npm/_logs/2020-09-25T15_10_10_126Z-debug.log
[builder]     
[builder] 
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 145
```

### Proposed implementation

1. During build phase,  see if the vendored/downloaded `node_modules` contain native extensions.
   
   This could be checked by detecting the [presence of the `binding.gyp` file](https://github.com/nodejs/node-gyp/tree/v7.1.0#the-bindinggyp-file) at the root of every module.
    E.g. https://github.com/paketo-buildpacks/npm-install/blob/v0.2.0/integration/testdata/vendored/node_modules/sqlite3/binding.gyp

2. If it contains native extensions, check for the build image supports compiling native extensions

    Maybe check for some heuristics like `python`

3. If the app contains native extensions and is using a build image that can't support compiling it, fail build with appropriate error message logged.

**Comment by kvedurmu** [comment]
This would be great. Even better if the error message can tell users to try again with the Full stack.

**Comment by arjun024** [comment]
After further discussion with paketo core team, it's best if we do not check for builder support in the build phase. We could simply elaborate the build failure log msg with a few common reasons for build failure instead.
