### ISSUE TITLE
A project with cached dependencies fails to start on subsequent builds

### ISSUE THREAD

**Issue by lance** [paketo-buildpacks/npm-install#375]
When building a project with npm dependencies, the first build succeeds and the image runs as expected. Subsequent builds complete successfully, but cached npm modules cannot be found when the container starts. This appears to only happen if there exists a package-lock.json file and the node_modules folder does not exist.

Possibly relevant
* When the package-lock.json file exists, but no node_modules folder exists, the buildpack command is `npm ci`. 
* When there exists a package-lock.json file and a node_modules folder, the command becomes `npm rebuild`.

## Expected Behavior

The cached dependencies should be available to the Node.js process when the container starts without requiring a build from a directory with dependencies installed locally.

## Current Behavior

When running a container from a project that has been built twice, with each build occurring without a local node_modules folder...
On container startup the cached dependencies cannot be found, and the user receives an error similar to that shown below.

```
❯ docker run --rm -p 8080:8080 -it quay.io/lanceball/bar
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'opossum'
Require stack:
- /workspace/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspace/index.js:2:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspace/index.js' ]
}
```

## Possible Solution

I have only just stumbled on this issue and have not dug into the buildpack to figure it out.

## Steps to Reproduce

1. Create a package.json file in an empty directory with the following contents. It doesn't matter what the dependency is, I'm just using `opossum` here because it's one I am familiar with and it has no dependencies of its own, so that should keep things simple.

```package.json
{
  "name": "bar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "opossum": "^6.4.0"
  }
}
```
2.  Create an index.js file in the same directory with the following contents. Not actually using the dependency here, just illustrating the problem.
```javascript
var http = require('http');
const A = require('opossum');

http.createServer(function (req, res) {
  res.write('Hello World!');
  res.end();
}).listen(8080);
```
3. Run `npm install && rm -rf node_modules` to generate a package-lock.json file for the project
4. Run `pack build --builder gcr.io/paketo-buildpacks/builder:base <image-name>` to build an image
5. Run the image `docker run --rm -it -p 8080:8080 <image-name>` - it works as expected. In another terminal you can run `curl http://localhost:8080` to confirm
6. Make a change to index.js
7. Re build with the same `pack` command above
8. Run the same `docker` command above
9. See an error
```
❯ docker run --rm -p 8080:8080 -it quay.io/lanceball/bar
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'opossum'
Require stack:
- /workspace/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspace/index.js:2:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspace/index.js' ]
}
```

## Motivations

It is causing user headaches in Knative Node.js function projects. See https://github.com/knative-sandbox/kn-plugin-func/issues/1131

**Comment by c0d1ngm0nk3y** [comment]
I could reproduce this with `0.10.3` of `npm-install`, but not anymore with `0.10.4`. So I guess this can be closed.
